{
    'name': 'Reportes Financieros y Fiscales Personalizados',
    'version': '18.0.1.0.0',
    'category': 'Accounting/Localizations',
    'summary': 'Módulo para la gestión de Relación de Cobranza, Cuadre Diario y Libros de Ventas SENIAT',
    'author': 'Custom Systems',
    'depends': [
        'base',
        'account',
    ],
    'data': [
        'security/ir.model.access.csv',
        'report/template_relacion_cobranza.xml',
        'report/template_resumen_libro_ventas.xml',
        'report/template_cuadre_diario.xml',
        'report/template_cuadre_diario_detalles.xml',
        'report/template_libro_ventas_diario.xml',
        'report/report_actions.xml',
        'views/relacion_cobranza_views.xml',
        'views/resumen_libro_ventas_views.xml',
        'views/cuadre_diario_views.xml',
        'views/cuadre_diario_detalles_views.xml',
        'views/libro_ventas_diario_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}